In [1]:
import pandas as pd 
df = pd.read_csv("products.csv")

In [2]:
print(df)

       product_id                                       product_name  \
0               1                         Chocolate Sandwich Cookies
1               2                                   All-Seasons Salt
2               3               Robust Golden Unsweetened Oolong Tea
3               4  Smart Ones Classic Favorites Mini Rigatoni Wit...
4               5                          Green Chile Anytime Sauce
...           ...                                                ...
49683       49684          Vodka, Triple Distilled, Twist of Vanilla
49684       49685                 En Croute Roast Hazelnut Cranberry
49685       49686                                   Artisan Baguette
49686       49687         Smartblend Healthy Metabolism Dry Cat Food
49687       49688                             Fresh Foaming Cleanser

       aisle_id  department_id
0            61             19
1           104             13
2            94              7
3            38              1
4             5             13
...         ...            ...
49683       124              5
49684        42              1
49685       112              3
49686        41              8
49687        73             11

[49688 rows x 4 columns]

In [3]:
df.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  str
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), str(1)
memory usage: 1.5 MB

In [5]:
df.isnull().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["product_id"].duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

product_id       49688
product_name     49688
aisle_id           134
department_id       21
dtype: int64

In [9]:
df.index

RangeIndex(start=0, stop=49688, step=1)

In [10]:
df.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id'], dtype='str')

In [11]:
df[["product_id", "aisle_id"]]

       product_id  aisle_id
0               1        61
1               2       104
2               3        94
3               4        38
4               5         5
...           ...       ...
49683       49684       124
49684       49685        42
49685       49686       112
49686       49687        41
49687       49688        73

[49688 rows x 2 columns]

In [12]:
df.iloc[0]

product_id                                1
product_name     Chocolate Sandwich Cookies
aisle_id                                 61
department_id                            19
Name: 0, dtype: object